version: '3.7'

services:
  nginx:
    image: nginx:1.17
    container_name: laravel.nginx
    hostname: laravel.nginx
    links:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/code:delegated

  php-fpm:
    build:
      context: ./.docker/php8.0-fpm
    container_name: laravel.api
    hostname: laravel.api
    working_dir: /code
    ports:
      - "9001:9001"
    volumes:
      - ./:/code:delegated
    links:
      - mysql
    environment:
      - PHP_IDE_CONFIG=serverName=laravel.api

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: laravel.db
    hostname: laravel.db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - laravel-mysql-data:/var/lib/mysql

  redis:
    image: redis:6.0
    container_name: laravel.redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: laravel.mongodb
    hostname: laravel.mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: laravel
      
  sonarqube:
    image: sonarqube
    container_name: laravel.sonarqube
    expose:
      - 9010
    ports:
      - "127.0.0.1:9010:9010"
    depends_on:
      - sonarqube-db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - ./docker/sonarqube/conf:/opt/sonarqube/conf
      - ./docker/sonarqube/logs:/opt/sonarqube/logs
      - laravel-sonarqube-data:/opt/sonarqube/data
    #      - sonarqube_extensions:/opt/sonarqube/extensions
    #      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

    sonarqube-db:
      image: postgres
      container_name: laravel.sonarqube-db
      environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar
      volumes:
        - laravel-sonarqube-db-data:/var/lib/postgresql/data

volumes:
  laravel-mysql-data:
  laravel-sonarqube-data:
  laravel-sonarqube-db-data: